enum StatusSolicitacao {
  criada,
  aguardandoPrestador,
  prestadorSelecionado,
  pagamentoPendente,
  pagamentoAprovado,
  agendado,
  aCaminho,
  emAndamento,
  concluido,
  avaliado,
  canceladoCliente,
  recusadoPrestador,
  canceladoPrestador,
  pagamentoRecusado,
}
